### ISSUE TITLE
Fix redirected links in Django

### ISSUE THREAD

**Issue by hanshal101** [hanshal101/Social-Welfare-HackOverflow#1]
Update all the files - views, urls , template folder

**Comment by JanaganSaravanan** [comment]
Hi!, Can I work on this issue?

**Comment by hanshal101** [comment]
Yes please

**Comment by JanaganSaravanan** [comment]
Hi! Can you please give me more information about the issue? Thanks.

**Comment by OsafAliSayed** [comment]
Hi let me work on this issue

**Comment by hanshal101** [comment]
Heyy @OsafAliSayed 
Thank you for your help but we are not working on this project anymore
